### ISSUE TITLE
Startup Issues

### ISSUE THREAD

**Issue by LogicalSoIutions** [LogicalSoIutions/Tarkov-Twitch-Bot#1]
When database gets around 99+ entries - https://pastebin.com/dcNBzEQe - The bot fails to work properly.

Also randomly the bot will throw this error for random channels upon starting - doesn't seem to affect anything

root@vps206857:~/wiki/twitch# python3 bot.py

`Task exception was never retrieved
future: <Task finished coro=<WebsocketConnection.join_action() done, defined at /usr/local/lib/python3.6/dist-packages/twitchio/websocket.py:543> exception=KeyError('teknokasap',)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/twitchio/websocket.py", line 553, in join_action
    self._pending_joins[channel].set_result(None)
KeyError: 'teknokasap'

Task exception was never retrieved
future: <Task finished coro=<WebsocketConnection.join_action() done, defined at /usr/local/lib/python3.6/dist-packages/twitchio/websocket.py:543> exception=KeyError('lvndmark',)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/twitchio/websocket.py", line 553, in join_action
    self._pending_joins[channel].set_result(None)
KeyError: 'lvndmark'`

**Comment by LogicalSoIutions** [comment]
99+ Entry timeout issue resolved
